### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TotalVerb** [TotalVerb/Remarkable.jl#5]
## Remarkable, General

- [x] Create the Remarkable.jl package
- [x] Move the Tags package to Remarkable
- [ ] Register the Remarkable.jl package

## Remarkable, Remark
- [x] Move the Remark engine to Remarkable.jl
- [x] Add remark
- [x] Add remarks
- [x] Deprecate the `#:text` keyword in favour of `include #:text`
- [x] Deprecate the `#:markdown` keyword in favour of `include #:markdown`
- [x] Deprecate the `#:include` keyword in favour of `include #:remark`
- [x] Deprecate the `#:define` keyword in favour of `remark` and `define`
- [x] Deprecate `include x #:object` in favour of `remark`
- [ ] Deprecate `include x #:keyword` in favour of `include x #:type keyword`
- [x] Deprecate the `#:execute` keyword in favour of `remark`
- [x] Deprecate the `#:var` keyword in favour of `remark`
- [x] Deprecate the `#:when x y` keyword in favour of ``remarks (when x `(y))``
- [ ] Deprecate the `#:each x y z` keyword in favour of `remarks (for/list ((x y)) z)`
- [x] Deprecate the `#:template` keyword in favour of a proper macro system
- [x] Ensure that `nothing` expands to no HTML
- [ ] Move to a multi-pass solution
